// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: spage/core/playbooks.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Playbook represents a playbook stored in the system
type Playbook struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Content     string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Optional pointer to the current bundle associated with this playbook
	CurrentBundleId string `protobuf:"bytes,7,opt,name=current_bundle_id,json=currentBundleId,proto3" json:"current_bundle_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Playbook) Reset() {
	*x = Playbook{}
	mi := &file_spage_core_playbooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playbook) ProtoMessage() {}

func (x *Playbook) ProtoReflect() protoreflect.Message {
	mi := &file_spage_core_playbooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playbook.ProtoReflect.Descriptor instead.
func (*Playbook) Descriptor() ([]byte, []int) {
	return file_spage_core_playbooks_proto_rawDescGZIP(), []int{0}
}

func (x *Playbook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Playbook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Playbook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Playbook) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Playbook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Playbook) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Playbook) GetCurrentBundleId() string {
	if x != nil {
		return x.CurrentBundleId
	}
	return ""
}

var File_spage_core_playbooks_proto protoreflect.FileDescriptor

const file_spage_core_playbooks_proto_rawDesc = "" +
	"\n" +
	"\x1aspage/core/playbooks.proto\x12\n" +
	"spage.core\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n" +
	"\bPlaybook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12*\n" +
	"\x11current_bundle_id\x18\a \x01(\tR\x0fcurrentBundleIdB6Z4github.com/AlexanderGrooff/spage-protobuf/spage/coreb\x06proto3"

var (
	file_spage_core_playbooks_proto_rawDescOnce sync.Once
	file_spage_core_playbooks_proto_rawDescData []byte
)

func file_spage_core_playbooks_proto_rawDescGZIP() []byte {
	file_spage_core_playbooks_proto_rawDescOnce.Do(func() {
		file_spage_core_playbooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spage_core_playbooks_proto_rawDesc), len(file_spage_core_playbooks_proto_rawDesc)))
	})
	return file_spage_core_playbooks_proto_rawDescData
}

var file_spage_core_playbooks_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spage_core_playbooks_proto_goTypes = []any{
	(*Playbook)(nil),              // 0: spage.core.Playbook
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_spage_core_playbooks_proto_depIdxs = []int32{
	1, // 0: spage.core.Playbook.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: spage.core.Playbook.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spage_core_playbooks_proto_init() }
func file_spage_core_playbooks_proto_init() {
	if File_spage_core_playbooks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spage_core_playbooks_proto_rawDesc), len(file_spage_core_playbooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spage_core_playbooks_proto_goTypes,
		DependencyIndexes: file_spage_core_playbooks_proto_depIdxs,
		MessageInfos:      file_spage_core_playbooks_proto_msgTypes,
	}.Build()
	File_spage_core_playbooks_proto = out.File
	file_spage_core_playbooks_proto_goTypes = nil
	file_spage_core_playbooks_proto_depIdxs = nil
}
